---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic
  namespace: petclinic
  labels:
    app: petclinic
    monitoring: enabled
spec:
  selector:
    matchLabels:
      app: petclinic
      monitoring: enabled

  namespaceSelector:
    matchNames:
      - petclinic

  endpoints:
    - port: management
      path: /actuator/prometheus
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
