apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
  namespace: petclinic
data:
  SPRING_PROFILES_ACTIVE: postgres
  POSTGRES_URL: jdbc:postgresql://postgres:5432/petclinic
  SPRING_SQL_INIT_MODE: never
