name: PetClinic CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build, test and analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          POSTGRES_DB: petclinic
          POSTGRES_USER: petclinic
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=raghadkhedhiri_spring-petclinic-devops
  sast-codeql:
    name: SAST - CodeQL
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java-kotlin

      - name: Build application for CodeQL
        run: ./mvnw -B -DskipTests package

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3

  container-security:
    name: Docker Build & Trivy Scan
    runs-on: ubuntu-latest
    needs: build-and-test

    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t petclinic-app:ci .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          version: 'v0.74.0'
          image-ref: 'petclinic-app:ci'
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'
          vuln-type: 'os,library'


      - name: Log in to GHCR
        if: github.event_name == 'push'
        env:
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$GHCR_TOKEN" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push Docker image to GHCR
        if: github.event_name == 'push'
        run: |
          docker tag petclinic-app:ci ghcr.io/${{ github.repository_owner }}/petclinic-app:${{ github.sha }}
          docker tag petclinic-app:ci ghcr.io/${{ github.repository_owner }}/petclinic-app:latest
          docker push ghcr.io/${{ github.repository_owner }}/petclinic-app:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/petclinic-app:latest
